# Generated by Django 6.0.5 on 2026-05-25 23:36

from django.db import migrations


def rename_permissions(apps, schema_editor):
    """Replace 'Can change' with 'Can edit' in all permission names."""
    Permission = apps.get_model('auth', 'Permission')
    for perm in Permission.objects.filter(codename__startswith='change_'):
        old_name = perm.name
        new_name = perm.name.replace('Can change', 'Can edit')
        if old_name != new_name:
            perm.name = new_name
            perm.save(update_fields=['name'])


def reverse_rename(apps, schema_editor):
    """Revert 'Can edit' back to 'Can change'."""
    Permission = apps.get_model('auth', 'Permission')
    for perm in Permission.objects.filter(codename__startswith='change_'):
        old_name = perm.name
        new_name = perm.name.replace('Can edit', 'Can change')
        if old_name != new_name:
            perm.name = new_name
            perm.save(update_fields=['name'])


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_post_migrate_setup"),
    ]

    operations = [
        migrations.RunPython(rename_permissions, reverse_rename),
    ]
